set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after
filetype plugin indent on

syntax on
set number
set title
set mouse=a
set tabstop=8
set softtabstop=8
set shiftwidth=8
set noexpandtab
set whichwrap=b,s,<,>,[,]
